### ISSUE TITLE
Pods fail to connect to the external database

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-example-foundation-app#69]
## Expected Behavior

Pod can connect to the external database

## Actual Behavior

pods fail to connect to the external database

it is necessary to Enable external ServiceEntry for database connection.
It is also possible to add an annotation to the deployments to exclude the CIDR range of the SQL servers from the istio-proxy

```
  template:
    metadata:
      labels:
        app: boa
        service: balancereader
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: "10.16.64.0/21"
```

## Steps to Reproduce the Problem

1. Follow all the instruction to deploy the foundation app

## Specifications

- Version: de00f4fe2540912949a6fc32691c14964211c2d3
- Platform: Ubuntu 20.04
